import {User} from '../models/user.model';

export const mockUsers: User[] = [
  {id: "1", username: "Arash", firstName: "", lastName: "", email: "arash@gmail.com", role: "user"},
  {id: "2", username: "Sara", firstName: "", lastName: "", email: "sara@gmail.com", role: "admin"},
  {id: "3", username: "Ali", firstName: "", lastName: "", email: "ali@gmail.com", role: "sysAdmin"},
  {id: "4", username: "Neda", firstName: "", lastName: "", email: "neda@gmail.com", role: "user"},
  {id: "5", username: "Omid", firstName: "", lastName: "", email: "omid@gmail.com", role: "user"},
  {id: "6", username: "Lara", firstName: "", lastName: "", email: "lara@gmail.com", role: "admin"},
  {id: "7", username: "Reza", firstName: "", lastName: "", email: "reza@gmail.com", role: "user"},
  {id: "8", username: "Mina", firstName: "", lastName: "", email: "mina@gmail.com", role: "user"},
  {id: "9", username: "Kia", firstName: "", lastName: "", email: "kia@gmail.com", role: "user"},
  {id: "10", username: "Leila", firstName: "", lastName: "", email: "leila@gmail.com", role: "sysAdmin"},
  {id: "11", username: "Sina", firstName: "", lastName: "", email: "sina@gmail.com", role: "user"},
  {id: "12", username: "Tara", firstName: "", lastName: "", email: "tara@gmail.com", role: "user"},
  {id: "13", username: "Hamed", firstName: "", lastName: "", email: "hamed@gmail.com", role: "admin"},
  {id: "14", username: "Shiva", firstName: "", lastName: "", email: "shiva@gmail.com", role: "user"},
  {id: "15", username: "Navid", firstName: "", lastName: "", email: "navid@gmail.com", role: "user"},
  {id: "16", username: "Yasmin", firstName: "", lastName: "", email: "yasmin@gmail.com", role: "sysAdmin"},
  {id: "17", username: "Farhad", firstName: "", lastName: "", email: "farhad@gmail.com", role: "user"},
  {id: "18", username: "Elahe", firstName: "", lastName: "", email: "elahe@gmail.com", role: "user"},
  {id: "19", username: "Kourosh", firstName: "", lastName: "", email: "kourosh@gmail.com", role: "user"},
  {id: "20", username: "Nima", firstName: "", lastName: "", email: "nima@gmail.com", role: "user"},
  {id: "21", username: "Sahar", firstName: "", lastName: "", email: "sahar@gmail.com", role: "admin"},
  {id: "22", username: "Pouya", firstName: "", lastName: "", email: "pouya@gmail.com", role: "user"},
  {id: "23", username: "Mitra", firstName: "", lastName: "", email: "mitra@gmail.com", role: "user"},
  {id: "24", username: "Shahram", firstName: "", lastName: "", email: "shahram@gmail.com", role: "sysAdmin"},
  {id: "25", username: "Negin", firstName: "", lastName: "", email: "negin@gmail.com", role: "user"},
  {id: "26", username: "Aria", firstName: "", lastName: "", email: "aria@gmail.com", role: "user"},
  {id: "27", username: "Ladan", firstName: "", lastName: "", email: "ladan@gmail.com", role: "user"},
];
